# Generated by Django 4.1.7 on 2023-03-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="write natural langauge for a book (e.g English, Frech, Germany etc",
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
